.TH YED-LANG-S 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/s \- Filetype for *.s files "assembly/asm".
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "S".
Matches buffer names *.S
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, assembly, asm, .s
